version: '3.9'
services:
  db:
    image: mariadb:10.6.14
    restart: always
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE:-change_me}
      - MARIADB_USER=${MARIADB_USER:-change_me}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-change_me}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-change_me}
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: {}
